on:
  issues:
    types: [labeled]

jobs:
  automate_invite:
    runs-on: ubuntu-latest
    steps:
      - name: Invite on label
        uses: vj-abigo/invite-on-label@v1.2
        with:
          organization: Design-and-Code
          label: Invitation
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          comment: '<b><h1>Welcome to the community🎉</h1></b><br>Don''t forget to accept the invitation sent through mail'
        env:
          INVITE_TOKEN: ${{ secrets.INVITE_TOKEN }}
